module.exports = {
  '0x8c9f364bf7a56ed058fc63ef81c6cf09c833e656':
    '<h5 className="mb-20">To Colin Goltra,</h5><p style="margin: 0 auto; max-width: 800px;">Thank you for being an early believer in my work, by collecting <b>&lsquo;Glory II&rsquo;</b>, you have contributed immensely in my life and I&rsquo;m eternally grateful. I&rsquo;d like to give you your flowers for also being a tremendous figure in the web3/Crypto space and I appreciate all you&rsquo;ve done for myself and many other artists. <br /> <br /> Love, Lethabo Huma <br /></p>',
  '0x9fdf724bcdf9392bd4b99a1c463ec674bc891bb9':
    '<h5 className="mb-20">To Cuy Sheffield,</h5><p style="margin: 0 auto; max-width: 800px;">My words disappear when I think of how to thank you for your contribution to my growth, you helped me connect to the space in a much deeper way and brought great value and attention to my work, you even rejected a Scott Belsky bid :D &ndash; <b>&lsquo;Midnight Blues&rsquo;</b> is in great hands &amp; hope for the decades to come, your family can enjoy it&rsquo;s possession. Through you and your belief in me and my work, I met my idol Micah Johnson and many other amazing artist&rsquo;s and contributors &ndash; You&rsquo;ve changed my life in more way&rsquo;s then anyone can believe.<br /><br />I&rsquo;d like to give you your flowers for your innovations in pushing boundaries in crypto &amp; for your prioritization in pushing BIPOC to the forefront in the crypto/NFT space.<br />It&rsquo;s amazing to see your ideas finally coming into fruition.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x1e815a8188f1b84564577c1c998f7e6b4706b752':
    '<h5 className="mb-20">To Allen,</h5><p style="margin: 0 auto; max-width: 800px;">Your belief in my work changed my life in many ways, firstly when you bought my <b>&lsquo;Child Mother&rsquo;</b> piece we connected profoundly as you mentioned you also have family in Africa, Liberia, as it was relatable because of the context of history it was associated with, in most African countries. Secondly, you assisted me out of my comfort zone by inviting me to your podcast, and the many other clubhouse which introduced me to a whole new world and few collectors &ndash; I&rsquo;m an introvert and normally reserved when I speak to people, but you made it easy for me.<br /><br />I&rsquo;d like to give you your flower&rsquo;s for being an amazing force in this digital world &ndash; and for opening it up for more people like myself.<br /></p>',
  '0x109ad81ca063fa1a8237189e31821d3114c52a4e':
    '<h5 className="mb-20">To Nanzo Scoop,</h5><p style="margin: 0 auto; max-width: 800px;">To the one that changed it all, the one that took a chance on my dreams, the one who sparked the fire to keep me going, for making me believe that being a digital artist is a real career, for contributing in changing my families life. I&rsquo;ll never forget the day, 8th December 2020 the day <b>&lsquo;See No Evil&rsquo;</b> was purchased, I was full of emotion, I cried and professed that I&rsquo;ll keep going, I&rsquo;ll keep creating &amp; won&rsquo;t ever take my gift for granted as there&rsquo;s people like yourself who believe and showed me that there&rsquo;s a path in NFTs.<br /><br />It&rsquo;s forever inscribed, its going to be a year since I began this journey, and my life has changed forever.<br />I&rsquo;d like to give you your flowers for giving me a chance to believe in myself and my abilities.<br /><br />Love, Lethabo Huma</p>',
  '0x75259686c1c967399eda0b4b16f16fb0990f9615':
    '<h5 className="mb-20">To Melrose Ghost,</h5><p style="margin: 0 auto; max-width: 800px;">Thank you for believing in my dream in waking up an emotion in you through my art.<br />Your contribution in my life has changed it immensely, you&rsquo;ve helped me believe in myself when I was still new in the NFT space &ndash; Thank you for collecting <b>&lsquo;Self , Escapism I, Bot Meets Human&rsquo;</b>.<br /><br />I&rsquo;d like to give you your flowers for constantly giving artists a chance to believe in themselves.<br /><br />Love, Lethabo Huma<br /></p>',
  '0xc571147a515a789eb23cbcbf92f86bc1485ab877':
    '<h5 className="mb-20">To Abefroman,</h5><p style="margin: 0 auto; max-width: 800px;">I&rsquo;m grateful for your presence in my journey of being an artist, with <b>&lsquo;BEAMING&rsquo;</b> I was experimenting with shapes, looking to express the depth of my creativity.<br /><br />I&rsquo;d like to give you your flowers for showing me that there&rsquo;s value in tapping into every fibre of self, through your purchase of this piece, you&rsquo;ve changed my life.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x30a189710f75c6b60b96081f12b288abededa260':
    '<h5 className="mb-20">To the xx1off Team,</h5><p style="margin: 0 auto; max-width: 800px;">Your contribution to my growth has changed my life, you&rsquo;ve shown me as a digital artist that I do carry value and that I matter &ndash; that all black digital artists matter.<br />I&rsquo;m highly grateful that you collected <b>&lsquo;Daydream &amp; Escapism II&rsquo;</b> and proud to be on this journey with you guys.<br /><br />I&rsquo;d like to give you your flowers for being trailblazers and not just highlighting but contributing to black NFT artist&rsquo;s lives.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x4e84a91a450aeef23f0670fb486d55b1d85a8dd0':
    '<h5 className="mb-20">To RoseGold</h5><p style="margin: 0 auto; max-width: 800px;">For believing in me and collecting <b>&lsquo;Eat Western&rsquo;</b> &ndash; you&rsquo;ve contributed to changing my life &amp; I&rsquo;d like to give you your flowers for taking a chance on a digital artist.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x3612b2e93b49f6c797066ca8c38b7f522b32c7cb':
    '<h5 className="mb-20">To Rudy Adler</h5><p style="margin: 0 auto; max-width: 800px;">For believing in me and collecting <b>&lsquo;Haitus&rsquo;</b> &ndash; you&rsquo;ve contributed to changing my life &amp; I&rsquo;d like to give you your flowers for taking a chance on a digital artist.<br /><br />Love, Lethabo Huma<br /></p>',
  '0xcf6f5a68d94165081a634ada997be3a93426c467':
    '<h5 className="mb-20">To Demar Edward,</h5><p style="margin: 0 auto; max-width: 800px;">Being part of the Christies: Natively digital made me believe that anything is possible, but when my piece <b>&lsquo;GOGO &amp; ME&rsquo;</b> sold at the auction it did not just entrench the belief but it also changed my life in a significant way, you mentioned how relatable it is as it reminded you of your grandma &amp; there&rsquo;s no better to connect with someone, as my grandma was my inspiration.<br /><br />I&rsquo;d like to give you your flowers for being a believer in me and my abilities, it&rsquo;s an honour to be part of your collection.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x8c94072567b278b9fa12192cca899b3ce0ed5fdc':
    '<h5 className="mb-20">To NFT Aficionado,</h5><p style="margin: 0 auto; max-width: 800px;">You&rsquo;ve been a true believer and consistent purveyor for black NFT art for, and you&rsquo;ve constantly fought for the high value of those who deserve it, while simultaneously changing Black artists lives, collecting avidly and blazing a trail for other black art collectors/collectives.<br />.<br />I&rsquo;m eternally grateful for the teams insights and belief in black art, and highly appreciate you for collecting <b>&lsquo;Monday Morning&rsquo;</b> &amp; &lsquo;Safe Haven&rsquo;<br /><br />You&rsquo;ve contributed so much in my life and I&rsquo;d like to give you your flowers for the immense support and pioneering spirit in the NFT &amp; Web3 world.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x8139ba1a21db4b924a81d5de90a98980b5d502e5':
    '<h5 className="mb-20">To Aki Abiola,</h5><p style="margin: 0 auto; max-width: 800px;">I remember the discussion we had about the NFT space and it was insightful and intriguing, but what was more impressive were your achievements &ndash; being part of Tate Musuem African Acquisition committee - I knew then how much of a believer you are in African Art and the people behind it. You&rsquo;re interest in collecting <b>&lsquo;HOPE&rsquo;</b> changed the trajectory of my life and I&rsquo;ll always be grateful for being part of your collection.<br /><br />I&rsquo;d like to give you your flowers for being an early believer and taking a chance of digital art, being a constant force for African art.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x0d48086911270b67bc973b7aa1a1332ef83dd472':
    '<h5 className="mb-20">To Jonathan Nakhla,</h5><p style="margin: 0 auto; max-width: 800px;">For believing in me and collecting <b>&lsquo;Coming Times&rsquo;</b> &ndash; you&rsquo;ve contributed to changing my life &amp; I&rsquo;d like to give you your flowers for taking a chance on a digital artist.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x80aa4af1fb6e8a381b73809cbf06aed2666a7b64':
    '<h5 className="mb-20">To Micah Johnson,</h5><p style="margin: 0 auto; max-width: 800px;">The first time we met virtually on Clubhouse, you got up on stage and mentioned how much you loved my work,and that meant so much to hear it coming from one of the greatest living artists of this day. <br />From that day, I should&rsquo;ve known that you&rsquo;ll change my life considerably. I&rsquo;m tremendously grateful for everything you&rsquo;ve done, not just for me, but for all people of color. You&rsquo;ve shown me that nothing I apply myself to is impossible &ndash; What you&rsquo;ve done with AKU Dreams will be celebrated for decades to come.<br /><br />Thank you for nominating me for the TIME Magazine: Build a better future Collection, words fail me from describing how much it opened doors and drew attention to my work and narrative.<br /><br />These are your flowers for imparting belief in me that all things are possible, for being a transformative force in the NFT/Crypto world and building a path for all Artists, especially black young boys and girls.<br /></p>',
  '0x7e66de1a57e6dc63b31ff03b50c103379c840d14':
    '<h5 className="mb-20">To Lady Phoenix,</h5><p style="margin: 0 auto; max-width: 800px;">A strong woman who has BLAZED through the NFT/Crypto space, A strong woman who has put others in front for the world to see and admire. The GOGO &amp; Me piece, came out beautiful, and it mostly was how you challenged and pushed me out of my comfort zone.<br /><br />Thank you for believing in my dream to bring value to the NFT space, and for always lifting those who need to be seen &ndash; you&rsquo;ve shown us what it means to be a strong black woman in this digital age, you&rsquo;re a PILLAR OF LOVE.<br /><br />You deserve your flowers as you gracefully conquer the world.<br />This piece is titled Pillar of Love.<br /><br />Love, Lethabo Huma<br /></p>',
  '0xeb758d7b02eb8adfaa553f49cfa8b034ab73c1c4':
    '<h5 className="mb-20">To Michael,</h5><p style="margin: 0 auto; max-width: 800px;">You&rsquo;ve changed my life in more ways than one and became the pillar to my growth as an artist, I appreciate for choosing me, I appreciate you for believing in me, I&rsquo;m eternally grateful for your presence in the NFT world &ndash; the significance you&rsquo;ve brought has changed the dynamic of how digital art is valued.<br /><br />You deserve your flower&rsquo;s as you keep building the future and changing lives<br />This piece is titled Pillar of Love<br /><br />Love, Lethabo Huma<br /></p>',
  '0xfc789c7927ac1cc8caefde8bebf493961ac5be9b':
    '<h5 className="mb-20">To David Johnson,</h5><p style="margin: 0 auto; max-width: 800px;">While building the anticipation for the NFTism drop, you were highly accommodating and made me comfortable throughout the drop, and witnessed how you&rsquo;re such an amazing community builder, in this NFT world, you&rsquo;re pioneering what few can achieve and that&rsquo;s why I&rsquo;m grateful for having crossed paths with you.<br /><br />I&rsquo;d like to give you your flowers for being such revolutionary in the age of web3.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x0f2f2f7bfc893ada1714802924f96b82c9a1ffd3':
    '<h5 className="mb-20">To Jonny Burt,</h5><p style="margin: 0 auto; max-width: 800px;">Thank you for seeing value in my work, and for being a pioneer in the NFT space &ndash; the space you&rsquo;ve built is safe, progressive and revolutionary. I&rsquo;ll always be grateful for being part of Institut.<br /><br />I&rsquo;d like to give you your flowers for being a true believer in art and artists across the world.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x215f7add9541bc097679d9237df7d42bb114134c':
    '<h5 className="mb-20">To Keith Grossman,</h5><p style="margin: 0 auto; max-width: 800px;">You&rsquo;re one of the pioneers of the web3 era, you&rsquo;ve taken a chance on a new digital age where many are skeptics, you have shown us that it&rsquo;s okay to be an outlier, that it&rsquo;s okay to carve a new lane that could potentially change the world &ndash; you took a bet on digital art and myself and I&rsquo;m forever grateful.<br /><br />Your warmth and accommodating spirit drew so many people to pay closer attention to you and your ideas to change the world, and for that I&rsquo;m eternally thankful to have crossed paths with you.<br /><br />The piece <b>&lsquo;SAFE HAVEN&rsquo;</b>, was inspired by our discussion we had when you mentioned something interesting your daughter asked you, and that was my north star and it changed my life.<br /><br />I&rsquo;d like to give you your flowers for building a better world through web3 technology and believing in a digital artist such as myself.<br /><br />Love, Lethabo Huma<br /></p>',
  '0xb3007ff3c3f40bdf0126fec7c8e43c3fc50ea813':
    '<h5 className="mb-20">To Zack,</h5><p style="margin: 0 auto; max-width: 800px;">In 2020 when I was just beginning to understand my path in the digital art world, you came along and significantly changed my life. You displayed immense generosity, and showed me everything a beginner needs to know when it came to putting out NFT&rsquo;s, you showed patience whenever I asked questions, you provided your insight when I couldn&rsquo;t decide on which piece to mint as my genesis for Superrare. You chose <b>&lsquo;Monday Blues&rsquo;</b> as you LOVED the Line work on it, and that changed my life considerably.<br /><br />I&rsquo;d like to give you your flower&rsquo;s for contributing to my career and being the few who has changed the world in the NFT space &ndash; the magnitude of your influence to many artists around the world is a $RARE occurrence.<br /><br />Love, Lethabo Huma<br /></p>',
  '0xdc1bc12a38206b010971859dc7177aff9d27c454':
    '<h5 className="mb-20">To Edwin,</h5><p style="margin: 0 auto; max-width: 800px;">Your patience and kindness has truly helped me understand the fundamentals of the new web3 technology, I&rsquo;m highly grateful for having crossed paths with you and helping me build my dream, you&rsquo;ve made it so easy and I&rsquo;m thankful for your contribution and understanding.<br /><br />These are your flowers for being an early-adopter, an innovator in the African web space &ndash; Keep going.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x5f0acde83f858014bc9723b356095e28fc8880b1':
    '<h5 className="mb-20">To Kingsley,</h5><p style="margin: 0 auto; max-width: 800px;">Truly grateful for your skills in building my dream, your aura is peaceful and calm, and It brought a great balance to the team in building the site. Thank you for your contributions and I&rsquo;m very happy we crossed paths.<br /><br />These are your flowers for being an OG developer in the African Web3 space &ndash; very lucky to have had you part of the team.<br /><br />Love, Lethabo Huma<br /></p>',
  '0x53c379a44018504059d01ee3eb9645cb115fd932':
    '<h5 className="mb-20">To Kingsley,</h5><p style="margin: 0 auto; max-width: 800px;">Truly grateful for your skills in building my dream, your aura is peaceful and calm, and It brought a great balance to the team in building the site. Thank you for your contributions and I&rsquo;m very happy we crossed paths.<br /><br />These are your flowers for being an OG developer in the African Web3 space &ndash; very lucky to have had you part of the team.<br /><br />Love, Lethabo Huma<br /></p>'
};
